[package]
name = "boids"
version = "0.1.0"
authors = ["vlad <vladov3000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34", features = [ "image" ] }
rand = "0.8.4"
